---
- name: Add repository | [Debian/Ubuntu]
  apt_repository:
    repo: "{{ haproxy_ppa_repo }}"
    update_cache: yes
    validate_certs: no
  when: ansible_pkg_mgr == 'apt' and haproxy_use_ppa == True

- name: Install HAProxy Packages
  package:
    name: "{{ haproxy_distro_packages }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

- name: Create haproxy conf.d dir
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  with_items:
    - { path: "/etc/haproxy" }
    - { path: "/etc/haproxy/conf.d" }

      #- name: Get files in conf.d directory
      #  find:
      #    path: "/etc/haproxy/conf.d"
      #  register: conf_files
      #
      #- name: Ensure conf.d directory is empty
      #  file:
      #    path: "{{ item.path }}"
      #    state: absent
      #  with_items: "{{ conf_files.files }}"

- name: Ensure runtime directory exists
  file:
    path: "/run/haproxy"
    state: directory
    owner: haproxy
    group: haproxy

- name: Create tmpfiles entry
  copy:
    content: "d /run/haproxy 2775 haproxy haproxy -"
    dest: "/etc/tmpfiles.d/haproxy.conf"
