<html>
<header><title>Service unavailable</title></header>
<style>
  body {
    background: #582583 }
  div.container {
    height: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center }
  div.container h2 {
    color: white; 
    margin: 1em }
</style>
<body>
<div class="container">
  <canvas id="soi" width="200" height="200"></canvas>
  <script>
    var canvas = document.getElementById('soi');
    var ctx = canvas.getContext('2d');
    ctx.beginPath();
    ctx.moveTo(0,0);
    ctx.lineTo(180,0);
    ctx.lineTo(180,180);
    ctx.lineTo(120,180);
    ctx.lineTo(120,120);
    ctx.lineTo(60,120);
    ctx.lineTo(60,180);
    ctx.lineTo(0,180);
    ctx.lineTo(0,120);
    ctx.lineTo(60,120);
    ctx.lineTo(60,60);
    ctx.lineTo(0,60);
    ctx.fillStyle = 'white';
    ctx.fill();
  </script>
  <h2>Service you are trying to reach is unavailable (405).</h2>
</div>
</body>
</html>
